# Generated by Django 3.2.5 on 2021-08-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='upload',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
