# Generated by Django 3.2.5 on 2021-08-29 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_menu_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuisine',
            fields=[
                ('typeid', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='type',
        ),
        migrations.AddField(
            model_name='menu',
            name='typeid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.cuisine'),
        ),
    ]
