# Generated by Django 3.2.5 on 2021-09-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210830_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='num',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
